export const VISUAL_NAMES={box:'Box',bottle:'Bottle',canister:'Canister',can:'Can / filter',battery:'Battery',bag:'Bag',tube:'Long part',pallet:'Pallet'};

export function inferVisualType(product={}){const text=`${product.name||''} ${product.category||''}`.toLowerCase();if(product.storageType==='pallet')return'pallet';if(/battery/.test(text))return'battery';if(/filter|can/.test(text))return'can';if(/oil|coolant|liquid/.test(text))return'bottle';if(/grease|canister|jug/.test(text))return'canister';if(/belt|wiper|shock absorber|radiator/.test(text))return'tube';if(/mat|bag/.test(text))return'bag';return'box'}

export function rackBayAxis(rack={}){if(rack.accessAxis==='x')return'z';if(rack.accessAxis==='z')return'x';return(Number(rack.depth)||0)>(Number(rack.length)||0)?'z':'x'}

export function rackSlotPosition(rack,bay,bays){const bayAxis=rackBayAxis(rack),span=bayAxis==='z'?rack.depth:rack.length,offset=-span/2+(bay+.5)*span/bays;return{x:(rack.x||0)+(bayAxis==='x'?offset:0),z:(rack.z||0)+(bayAxis==='z'?offset:0),localX:bayAxis==='x'?offset:0,localZ:bayAxis==='z'?offset:0,bayAxis}}

export function rackSlotDimensions(rack,bays,levels){const bayAxis=rackBayAxis(rack),rackHeight=1.05+levels*.72,levelGap=(rackHeight-.25)/levels,baySpan=bayAxis==='z'?rack.depth:rack.length,rackFaceDepth=bayAxis==='z'?rack.length:rack.depth;return{width:Math.max(.08,baySpan/bays-.06),depth:Math.max(.08,rackFaceDepth-.16),height:Math.max(.08,levelGap-.08),rackHeight,levelGap,bayAxis}}

export function productVisualSize(product,rack,slot,bays,levels){const cell=rackSlotDimensions(rack,bays,levels),along=cell.width*(.68+(slot.bay%3)*.05),across=cell.depth*(.52+(slot.level%2)*.08),height=Math.min(cell.height*.62,Math.max(.30,(Number(product.packageHeightM)||.15)*1.9));return{width:cell.bayAxis==='z'?across:along,depth:cell.bayAxis==='z'?along:across,height}}

/* ---------- Procedural texture atlas ----------
   Every product is a rectangular carton. Each type paints a 512×512 atlas with four 256×256 regions:
   top-left = lid, top-right = base, bottom-left = long sides, bottom-right = short ends.
   BoxGeometry UVs are remapped so each face samples its own region. Textures are drawn in light greys so the
   product colour assigned by the app tints them; a bump map made from the same atlas adds relief. */
const Q=256,ATLAS=512;
const MATERIAL_PRESETS={box:{roughness:.86,metalness:0,bump:.35},bottle:{roughness:.7,metalness:0,bump:.4},canister:{roughness:.36,metalness:.04,bump:.2},can:{roughness:.8,metalness:0,bump:.3},battery:{roughness:.62,metalness:.05,bump:.25},bag:{roughness:.94,metalness:0,bump:.5},tube:{roughness:.84,metalness:0,bump:.3},pallet:{roughness:.5,metalness:.02,bump:.35}};

function rng(seed){let s=seed>>>0||1;return()=>{s=(s*1664525+1013904223)>>>0;return s/4294967296}}
function region(ctx,col,row,paint){ctx.save();ctx.translate(col*Q,row*Q);ctx.beginPath();ctx.rect(0,0,Q,Q);ctx.clip();paint(ctx);ctx.restore()}
function noise(ctx,alpha,scale,seed,dark=true){const rand=rng(seed),c=dark?0:255;for(let y=0;y<Q;y+=scale)for(let x=0;x<Q;x+=scale){ctx.fillStyle=`rgba(${c},${c},${c},${(rand()*alpha).toFixed(3)})`;ctx.fillRect(x,y,scale,scale)}}
function edge(ctx,alpha=.22,size=5){ctx.fillStyle=`rgba(0,0,0,${alpha})`;ctx.fillRect(0,0,Q,size);ctx.fillRect(0,Q-size,Q,size);ctx.fillRect(0,0,size,Q);ctx.fillRect(Q-size,0,size,Q)}
function cardboard(ctx,tone='#d9d4c8',seed=11){ctx.fillStyle=tone;ctx.fillRect(0,0,Q,Q);noise(ctx,.10,2,seed);noise(ctx,.06,6,seed+1,false);ctx.fillStyle='rgba(0,0,0,.09)';for(let y=0;y<Q;y+=3)ctx.fillRect(0,y,Q,1);edge(ctx)}
function tape(ctx,vertical=false){ctx.fillStyle='rgba(255,255,255,.42)';ctx.fillRect(vertical?Q*.44:0,vertical?0:Q*.44,vertical?Q*.12:Q,vertical?Q:Q*.12);ctx.fillStyle='rgba(0,0,0,.14)';if(vertical){ctx.fillRect(Q*.44,0,2,Q);ctx.fillRect(Q*.56-2,0,2,Q)}else{ctx.fillRect(0,Q*.44,Q,2);ctx.fillRect(0,Q*.56-2,Q,2)}}
function straps(ctx,xs){for(const x of xs){ctx.fillStyle='#2b3038';ctx.fillRect(x-6,0,12,Q);ctx.fillStyle='rgba(255,255,255,.2)';ctx.fillRect(x-1,0,2,Q)}}
function film(ctx){const g=ctx.createLinearGradient(0,0,Q,Q);g.addColorStop(0,'rgba(255,255,255,.26)');g.addColorStop(.38,'rgba(255,255,255,0)');g.addColorStop(.6,'rgba(255,255,255,.14)');g.addColorStop(1,'rgba(255,255,255,0)');ctx.fillStyle=g;ctx.fillRect(0,0,Q,Q)}
function text(ctx,str,x,y,size,color='#3a3f47',weight=700,align='center'){ctx.fillStyle=color;ctx.font=`${weight} ${size}px "Manrope",sans-serif`;ctx.textAlign=align;ctx.textBaseline='middle';ctx.fillText(str,x,y)}
function labelPlate(ctx,x,y,w,h,code,accent='#1c2430'){ctx.fillStyle='#f6f7f5';ctx.fillRect(x,y,w,h);ctx.strokeStyle=accent;ctx.lineWidth=3;ctx.strokeRect(x+1.5,y+1.5,w-3,h-3);ctx.fillStyle=accent;ctx.font=`900 ${Math.round(h*.46)}px "JetBrains Mono",ui-monospace,monospace`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(code,x+w/2,y+h*.36);const rand=rng(code.length*7919+w);let bx=x+w*.12;const by=y+h*.66,bh=h*.22;while(bx<x+w*.88){const bw=1+Math.floor(rand()*3);ctx.fillRect(bx,by,bw,bh);bx+=bw+1+Math.floor(rand()*3)}}
function hazardStripe(ctx,y,h){ctx.save();ctx.beginPath();ctx.rect(0,y,Q,h);ctx.clip();ctx.fillStyle='#262b33';ctx.fillRect(0,y,Q,h);ctx.fillStyle='#e6e9ee';for(let x=-h;x<Q+h;x+=h*1.6){ctx.beginPath();ctx.moveTo(x,y+h);ctx.lineTo(x+h*.8,y+h);ctx.lineTo(x+h*1.8,y);ctx.lineTo(x+h,y);ctx.closePath();ctx.fill()}ctx.restore()}
function caps(ctx,cols,rows,r,fill='#e8ebef',ring='#8a929e'){const gx=Q/cols,gy=Q/rows;for(let i=0;i<cols;i++)for(let j=0;j<rows;j++){const cx=gx*(i+.5),cy=gy*(j+.5);ctx.fillStyle='rgba(0,0,0,.4)';ctx.beginPath();ctx.arc(cx+2,cy+3,r,0,Math.PI*2);ctx.fill();ctx.fillStyle=fill;ctx.beginPath();ctx.arc(cx,cy,r,0,Math.PI*2);ctx.fill();ctx.strokeStyle=ring;ctx.lineWidth=3;ctx.beginPath();ctx.arc(cx,cy,r*.68,0,Math.PI*2);ctx.stroke();ctx.fillStyle='rgba(255,255,255,.45)';ctx.beginPath();ctx.arc(cx-r*.3,cy-r*.32,r*.2,0,Math.PI*2);ctx.fill()}}
function window_(ctx,x,y,w,h){ctx.fillStyle='#262b33';ctx.fillRect(x,y,w,h);ctx.fillStyle='rgba(0,0,0,.35)';ctx.fillRect(x,y,w,6);ctx.fillRect(x,y,6,h)}
function bottles(ctx,x,y,w,h,count){const bw=w/count;for(let i=0;i<count;i++){const cx=x+bw*(i+.5),neckW=bw*.22,bodyW=bw*.62;ctx.fillStyle='#d7dbe0';ctx.fillRect(cx-neckW/2,y+h*.08,neckW,h*.26);ctx.fillStyle='#2f353d';ctx.fillRect(cx-neckW/2-2,y+h*.04,neckW+4,h*.09);ctx.fillStyle='#cfd4da';ctx.beginPath();ctx.moveTo(cx-neckW/2,y+h*.34);ctx.lineTo(cx-bodyW/2,y+h*.46);ctx.lineTo(cx-bodyW/2,y+h);ctx.lineTo(cx+bodyW/2,y+h);ctx.lineTo(cx+bodyW/2,y+h*.46);ctx.lineTo(cx+neckW/2,y+h*.34);ctx.closePath();ctx.fill();ctx.fillStyle='rgba(255,255,255,.35)';ctx.fillRect(cx-bodyW/2+3,y+h*.5,4,h*.45);ctx.fillStyle='#1c2430';ctx.fillRect(cx-bodyW/2,y+h*.62,bodyW,h*.2)}}
function slats(ctx,y,h,count){const w=Q/count;ctx.fillStyle='rgba(0,0,0,.28)';for(let i=1;i<count;i++)ctx.fillRect(i*w-3,y,6,h);ctx.fillStyle='rgba(255,255,255,.18)';for(let i=0;i<count;i++)ctx.fillRect(i*w+4,y,2,h)}
function cartonGrid(ctx,cols,rows,tone='#cfc9bb',seed=61){ctx.fillStyle='#2a2f37';ctx.fillRect(0,0,Q,Q);const gw=Q/cols,gh=Q/rows;for(let i=0;i<cols;i++)for(let j=0;j<rows;j++){ctx.save();ctx.translate(i*gw+3,j*gh+3);ctx.beginPath();ctx.rect(0,0,gw-6,gh-6);ctx.clip();ctx.fillStyle=tone;ctx.fillRect(0,0,gw,gh);ctx.fillStyle='rgba(0,0,0,.1)';for(let y=0;y<gh;y+=3)ctx.fillRect(0,y,gw,1);ctx.fillStyle='rgba(0,0,0,.2)';ctx.fillRect(0,0,gw-6,3);ctx.fillRect(0,0,3,gh-6);ctx.restore()}noise(ctx,.08,3,seed)}
function planks(ctx,y,h){ctx.fillStyle='#b9a888';ctx.fillRect(0,y,Q,h);ctx.fillStyle='rgba(0,0,0,.14)';for(let yy=y;yy<y+h;yy+=4)ctx.fillRect(0,yy,Q,1);ctx.fillStyle='#1f242c';ctx.fillRect(0,y+h*.3,Q,h*.1);ctx.fillStyle='#8d7a5a';ctx.fillRect(0,y+h*.4,Q,h*.6);ctx.fillStyle='#1f242c';ctx.fillRect(Q*.22,y+h*.4,Q*.2,h*.6);ctx.fillRect(Q*.58,y+h*.4,Q*.2,h*.6)}

const PAINTERS={
  box(ctx){region(ctx,0,0,c=>{cardboard(c);tape(c);text(c,'↑↑',Q*.18,Q*.22,26,'#3a3f47',900)});region(ctx,1,0,c=>cardboard(c,'#c6c0b3',14));
    region(ctx,0,1,c=>{cardboard(c);labelPlate(c,Q*.22,Q*.58,Q*.56,Q*.3,'BOX');text(c,'THIS SIDE UP  ↑↑',Q*.08,Q*.2,15,'#3a3f47',700,'left');text(c,'FRAGILE · DO NOT STACK ABOVE 4',Q*.08,Q*.34,11,'#3a3f47',700,'left')});
    region(ctx,1,1,c=>{cardboard(c,'#d9d4c8',17);labelPlate(c,Q*.25,Q*.32,Q*.5,Q*.3,'BOX');text(c,'↑↑',Q*.5,Q*.8,26,'#3a3f47',900)})},
  bottle(ctx){region(ctx,0,0,c=>{c.fillStyle='#3a3f47';c.fillRect(0,0,Q,Q);c.fillStyle='rgba(0,0,0,.4)';c.fillRect(0,0,Q,Q*.06);c.fillRect(0,0,Q*.06,Q);caps(c,4,3,22);edge(c,.35,8)});region(ctx,1,0,c=>cardboard(c,'#c6c0b3',24));
    region(ctx,0,1,c=>{cardboard(c,'#cfc9bb',21);window_(c,Q*.06,Q*.12,Q*.88,Q*.5);bottles(c,Q*.08,Q*.12,Q*.84,Q*.5,6);slats(c,Q*.12,Q*.5,6);labelPlate(c,Q*.22,Q*.68,Q*.56,Q*.26,'BOT');text(c,'12 × 1 L',Q*.9,Q*.8,12,'#3a3f47',800,'right')});
    region(ctx,1,1,c=>{cardboard(c,'#cfc9bb',27);window_(c,Q*.1,Q*.12,Q*.8,Q*.5);bottles(c,Q*.12,Q*.12,Q*.76,Q*.5,3);slats(c,Q*.12,Q*.5,3);labelPlate(c,Q*.28,Q*.68,Q*.44,Q*.26,'BOT')})},
  canister(ctx){region(ctx,0,0,c=>{c.fillStyle='#dfe2e5';c.fillRect(0,0,Q,Q);const gw=Q/3,gh=Q/2;for(let i=0;i<3;i++)for(let j=0;j<2;j++){const x=i*gw+8,y=j*gh+8;c.fillStyle='rgba(0,0,0,.18)';c.fillRect(x,y,gw-16,gh-16);c.fillStyle='#cfd3d8';c.fillRect(x+4,y+4,gw-24,gh-24);c.fillStyle='#262b33';c.fillRect(x+gw/2-22,y+gh/2-16,36,32);c.fillStyle='#8a929e';c.fillRect(x+gw/2-16,y+gh/2-10,24,20)}film(c);edge(c,.2)});region(ctx,1,0,c=>cardboard(c,'#c6c0b3',34));
    region(ctx,0,1,c=>{c.fillStyle='#dfe2e5';c.fillRect(0,0,Q,Q);noise(c,.06,4,31);c.fillStyle='rgba(0,0,0,.14)';for(let i=0;i<3;i++){const x=i*Q/3+8;c.fillRect(x,Q*.12,Q/3-16,Q*.6);c.fillStyle='#cfd3d8';c.fillRect(x+4,Q*.14,Q/3-24,Q*.56);c.fillStyle='rgba(0,0,0,.14)'}hazardStripe(c,Q*.86,Q*.14);labelPlate(c,Q*.2,Q*.3,Q*.6,Q*.3,'CAN','#262b33');film(c)});
    region(ctx,1,1,c=>{c.fillStyle='#dfe2e5';c.fillRect(0,0,Q,Q);noise(c,.06,4,37);hazardStripe(c,Q*.86,Q*.14);labelPlate(c,Q*.25,Q*.32,Q*.5,Q*.3,'CAN','#262b33');film(c)})},
  can(ctx){region(ctx,0,0,c=>{cardboard(c,'#d9d4c8',41);c.fillStyle='rgba(0,0,0,.08)';c.fillRect(Q*.05,Q*.05,Q*.9,Q*.9);caps(c,3,3,30,'#8b9098','#3a3f47');text(c,'FILTERS',Q*.5,Q*.96,11,'#3a3f47',900)});region(ctx,1,0,c=>cardboard(c,'#c6c0b3',44));
    region(ctx,0,1,c=>{cardboard(c,'#d9d4c8',43);window_(c,Q*.06,Q*.14,Q*.88,Q*.42);const r=Q*.15;for(let i=0;i<4;i++){const cx=Q*.06+Q*.88*(i+.5)/4,cy=Q*.35;c.fillStyle='#9aa0a8';c.beginPath();c.arc(cx,cy,r,0,Math.PI*2);c.fill();c.strokeStyle='#3a3f47';c.lineWidth=3;for(let k=1;k<=3;k++){c.beginPath();c.arc(cx,cy,r*k/3.6,0,Math.PI*2);c.stroke()}}labelPlate(c,Q*.22,Q*.64,Q*.56,Q*.28,'FLT','#262b33')});
    region(ctx,1,1,c=>{cardboard(c,'#d9d4c8',47);labelPlate(c,Q*.25,Q*.3,Q*.5,Q*.3,'FLT','#262b33');text(c,'12 PCS',Q*.5,Q*.78,14,'#3a3f47',900)})},
  battery(ctx){region(ctx,0,0,c=>{cardboard(c,'#cfd3d9',51);hazardStripe(c,Q*.08,Q*.1);c.fillStyle='#262b33';c.fillRect(Q*.14,Q*.3,Q*.28,Q*.4);c.fillRect(Q*.58,Q*.3,Q*.28,Q*.4);text(c,'+',Q*.28,Q*.5,44,'#e94b3c',900);text(c,'−',Q*.72,Q*.5,44,'#e6e9ee',900);text(c,'12V · KEEP UPRIGHT',Q*.5,Q*.86,14,'#3a3f47',800)});region(ctx,1,0,c=>cardboard(c,'#bfc4cc',54));
    region(ctx,0,1,c=>{cardboard(c,'#cfd3d9',53);hazardStripe(c,Q*.1,Q*.08);labelPlate(c,Q*.16,Q*.32,Q*.68,Q*.34,'BAT','#262b33');text(c,'12V · KEEP UPRIGHT · ⚠',Q*.5,Q*.84,13,'#3a3f47',800)});
    region(ctx,1,1,c=>{cardboard(c,'#cfd3d9',57);hazardStripe(c,Q*.1,Q*.08);labelPlate(c,Q*.22,Q*.34,Q*.56,Q*.32,'BAT','#262b33');text(c,'⚠ 12V',Q*.5,Q*.84,14,'#3a3f47',900)})},
  bag(ctx){const folds=(c,seed)=>{c.fillStyle='#e2e0da';c.fillRect(0,0,Q,Q);noise(c,.14,3,seed);const rand=rng(seed+2);c.strokeStyle='rgba(0,0,0,.18)';c.lineWidth=2;for(let i=0;i<8;i++){c.beginPath();c.moveTo(rand()*Q,0);c.bezierCurveTo(rand()*Q,Q*.3,rand()*Q,Q*.7,rand()*Q,Q);c.stroke()}};
    region(ctx,0,0,c=>{folds(c,61);c.fillStyle='rgba(0,0,0,.28)';c.fillRect(0,Q*.46,Q,Q*.08);c.fillStyle='rgba(255,255,255,.5)';for(let x=0;x<Q;x+=8)c.fillRect(x,Q*.485,3,Q*.03)});region(ctx,1,0,c=>folds(c,64));
    region(ctx,0,1,c=>{folds(c,63);c.fillStyle='rgba(0,0,0,.25)';c.fillRect(0,0,Q,Q*.08);c.fillStyle='rgba(255,255,255,.4)';for(let x=0;x<Q;x+=8)c.fillRect(x,Q*.03,3,Q*.02);labelPlate(c,Q*.2,Q*.36,Q*.6,Q*.3,'BAG','#2a2f37');text(c,'25 KG',Q*.5,Q*.8,16,'#3a3f47',900)});
    region(ctx,1,1,c=>{folds(c,67);c.fillStyle='rgba(0,0,0,.25)';c.fillRect(0,0,Q,Q*.08);labelPlate(c,Q*.25,Q*.36,Q*.5,Q*.3,'BAG','#2a2f37')})},
  tube(ctx){region(ctx,0,0,c=>{cardboard(c,'#d9d4c8',71);straps(c,[Q*.25,Q*.75]);text(c,'◄  LONG PART  ►',Q*.5,Q*.5,15,'#3a3f47',900)});region(ctx,1,0,c=>{cardboard(c,'#c6c0b3',74);straps(c,[Q*.25,Q*.75])});
    region(ctx,0,1,c=>{cardboard(c,'#d9d4c8',73);straps(c,[Q*.25,Q*.75]);labelPlate(c,Q*.34,Q*.3,Q*.32,Q*.32,'TUB','#262b33');text(c,'DO NOT BEND',Q*.5,Q*.8,13,'#3a3f47',900)});
    region(ctx,1,1,c=>{cardboard(c,'#d9d4c8',77);labelPlate(c,Q*.25,Q*.34,Q*.5,Q*.32,'TUB','#262b33')})},
  pallet(ctx){region(ctx,0,0,c=>{cartonGrid(c,2,2,'#cfc9bb',81);film(c)});region(ctx,1,0,c=>planks(c,0,Q));
    region(ctx,0,1,c=>{c.save();c.beginPath();c.rect(0,0,Q,Q*.78);c.clip();cartonGrid(c,3,3,'#cfc9bb',83);c.restore();planks(c,Q*.78,Q*.22);labelPlate(c,Q*.24,Q*.3,Q*.52,Q*.22,'PAL','#2a2f37');film(c)});
    region(ctx,1,1,c=>{c.save();c.beginPath();c.rect(0,0,Q,Q*.78);c.clip();cartonGrid(c,2,3,'#cfc9bb',87);c.restore();planks(c,Q*.78,Q*.22);labelPlate(c,Q*.28,Q*.3,Q*.44,Q*.22,'PAL','#2a2f37');film(c)})}
};

const textureCache=new WeakMap();
function paint(type){const c=document.createElement('canvas');c.width=c.height=ATLAS;const ctx=c.getContext('2d');(PAINTERS[type]||PAINTERS.box)(ctx);return c}
function productTexture(THREE,renderer,type){let cache=textureCache.get(renderer);if(!cache){cache=new Map();textureCache.set(renderer,cache)}if(cache.has(type))return cache.get(type);const map=new THREE.CanvasTexture(paint(type));map.colorSpace=THREE.SRGBColorSpace;map.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());const bump=new THREE.CanvasTexture(paint(type));bump.anisotropy=map.anisotropy;const entry={map,bump};cache.set(type,entry);return entry}

/* BoxGeometry face order: +x, -x, +y, -y, +z, -z. Ends (±x) → bottom-right region, lid (+y) → top-left, base (−y) → top-right, long sides (±z) → bottom-left. */
const FACE_REGIONS=[[.5,0],[.5,0],[0,.5],[.5,.5],[0,0],[0,0]];
function cartonGeometry(THREE,visual){const geometry=new THREE.BoxGeometry(visual.width,visual.height,visual.depth),uv=geometry.attributes.uv;for(let face=0;face<6;face++){const [ox,oy]=FACE_REGIONS[face];for(let i=0;i<4;i++){const k=face*4+i;uv.setXY(k,ox+uv.getX(k)*.5,oy+uv.getY(k)*.5)}}uv.needsUpdate=true;return geometry}

export function createProductVisual(THREE,{renderer,product,visual,color,group}){const type=VISUAL_NAMES[product.visualType]?product.visualType:inferVisualType(product),textures=productTexture(THREE,renderer,type),preset=MATERIAL_PRESETS[type]||MATERIAL_PRESETS.box,material=new THREE.MeshStandardMaterial({color,map:textures.map,bumpMap:textures.bump,bumpScale:preset.bump*.01,roughness:preset.roughness,metalness:preset.metalness}),mesh=new THREE.Mesh(cartonGeometry(THREE,visual),material);mesh.castShadow=true;mesh.receiveShadow=true;if(group)group.add(mesh);return mesh}
